CREATE TABLE IF NOT EXISTS PATIENT_DETAILS (
  ID INT(11) AUTO_INCREMENT,
  FIRST_NAME varchar(100) NOT NULL,
  LAST_NAME varchar(100),
  AGE INT(2) NOT NULL,
  GENDER varchar(10) NOT NULL,
  MOBILE_NO varchar(15),
  EMAIL_ID varchar(100),
  ADDRESS varchar(1000),
  CITY VARCHAR(30) NOT NULL,
  STATE VARCHAR(30) NOT NULL,
  PINCODE int NOT NULL,
  EMERGENCY_CONTACT_NAME varchar(100),
  EMERGENCY_CONACT_NO varchar(15),
  PRIMARY KEY (ID)
);

INSERT INTO PATIENT_DETAILS (FIRST_NAME, LAST_NAME, AGE, GENDER, MOBILE_NO, EMAIL_ID, ADDRESS, CITY, STATE, PINCODE)
VALUES ('Rupali', 'Raniwala', 20, 'Female', '999999999', 'rupali@email.com', 'Purva Fountain', 'Bangalore', 'Karnataka', 560037);
INSERT INTO PATIENT_DETAILS (FIRST_NAME, LAST_NAME, AGE, GENDER, MOBILE_NO, EMAIL_ID, ADDRESS, CITY, STATE, PINCODE)
VALUES ('Avantika', 'Raniwala', 20, 'Female', '999999999', 'rupali@email.com', 'Purva Fountain', 'Bangalore', 'Karnataka', 560037);
SELECT * from PATIENT_DETAILS;
CREATE TABLE IF NOT EXISTS MEDICAL_HISTORY(
PREVIOUS_MEDICAL_CONDITIONS VARCHAR(10),
LAST_CHECKUP VARCHAR(30),
CHANGE_GENERAL_HEALTH VARCHAR(100),
MEDICATIONS VARCHAR(100) NOT NULL,
ALLERGIES VARCHAR(100),
ADVERSE_REACTIONS VARCHAR(150),
ASTHMA VARCHAR(10),
HEART_BP VARCHAR(10),
HEART_INFO VARCHAR(25),
PROSTHETICS VARCHAR(10),
IMMUNE_SYS_CONDITIONS VARCHAR(30),
HEP_JAUN_LIVER VARCHAR(10),
BLEEDING_PROBLEMS VARCHAR(10),
PREVIOUS_HOSPITALIZATIONS VARCHAR(30),
PREVIOUS_OPERATIONS VARCHAR(30),
FAMILY_DISEASES VARCHAR(20),
TOBACCO_OR_DRINKING VARCHAR(15),
PERIOD_HISTORY_WOMEN VARCHAR(10)
);



